### ISSUE TITLE
Hostname FQDN & comment misaligned

### ISSUE THREAD

**Issue by irwins** [Stephanevg/HostsFileManagement#1]
![image](https://cloud.githubusercontent.com/assets/10112589/25778760/0a007246-3308-11e7-97ce-6b90251289aa.png)

Looking at the result. the hostname would be rhino and the fqdn rhino.acme.com. Did you want to omit the # in the comment?

**Comment by Stephanevg** [comment]
Thanks for feedback Irwin!
Could it be that you started with the FQDN followed by the simple hostName?
 Could you copy and paste the exact line that you put in the Hosts file so that I could try it out.

**Comment by irwins** [comment]
Sure! No problem!!!

**Comment by Stephanevg** [comment]
The '#' from the comment is actually not visible in the object, but is written again when it hosts entries are persisted to file.
@irwins could you provide the hosts file you have used for your tests?

**Comment by Stephanevg** [comment]
Hey, what's up @irwins ?

For some reason, I totally skipped this issue. I can put some time in it now, plus, I would like to push this repo via 'Hacktoberfest', and try to have more people involved in it.

## Concerning your PR: 
I think actually that this should be tracked here, and examples of failing things, should actually not be a part of the productive repo. I took the examples over from your PR (https://github.com/Stephanevg/Class.HostsManagement/pull/3) and will close it without merging it. 

If you think something is missing, or we can add more info to id, please don't hesitate to comment.



## Hosts02
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
   102.54.94.97     rhino.acme.com          # source server
    38.25.63.10      x.acme.com              # x client host
    302.54.94.97     rhino.acme.com          # invalid source server
    238.25.630.10    x.acme.com              # invalid x client host
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
```

## Hosts03 

```text
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
102.54.94.97     rhino.acme.com          # source server
38.25.63.10     x.acme.com              # x client host
 # localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
```

**Comment by Stephanevg** [comment]
Closing this issue. If problem persists, please repopen it.
