### ISSUE TITLE
Invalid IPAddress throws and stops.

### ISSUE THREAD

**Issue by irwins** [Stephanevg/HostsFileManagement#2]
If stumbled on an invalid IP Address do you want it to stop or continue?
This was one of quirks Tobias talked about... 😁 

Here's something to think about:
```PowerShell
Class parseIPAddress{
   $IPAddress

   parseIPAddress($ipv4){
      $this.IPAddress = ($ipv4 -as [IPAddress]).IPAddressToString
   }
}

[parseIPAddress]::new('38.25.63.10')
[parseIPAddress]::new('380.25.63.10')

Class parseIPAddressThrow{
   $IPAddress

   parseIPAddressThrow($ipv4){
      $this.IPAddress = ([IPAddress]$ipv4).IPAddressToString
   }
}

[parseIPAddressThrow]::new('38.25.63.10')
[parseIPAddressThrow]::new('380.25.63.10')
```
![image](https://cloud.githubusercontent.com/assets/10112589/25778868/116115c4-330b-11e7-86a9-e3c2cfe71e06.png)

**Comment by Stephanevg** [comment]
In my eyes, if it is already in the HostsFile, then we should throw an exception. (or minimal would be a warning message.

If it is creating an entry using one of the constructors of [HostsEntry], It should throw an error, definitley. 
This functionality is actually already in the this class if I am not mistaken. By casting it to [IpAddress] it will not allow you to set an invalid Ip address as showed below:

![image](https://cloud.githubusercontent.com/assets/6302961/25782241/2b52c928-3347-11e7-9798-acf9b9196f26.png)
Is that what you had in mind?

**Comment by Stephanevg** [comment]
I added two new tests here -> https://github.com/Stephanevg/Class.HostsManagement/commit/22500f9e08ab159a6c8eb6ec2b801d84f3420312 That actually tests that it correctly throws an error when a wrong type of IP address is passed to the constructor of [HostsEntry].

**Comment by irwins** [comment]
> In my eyes, if it is already in the Hosts File, then we should throw an exception. (or minimal would be a warning message.
Good one! The host file can still be edited manually with invalid data. You could also use it to parse if the Hosts file is valid and re-mediate any issues found.

**Comment by Stephanevg** [comment]
I'll close this issue since the error handling on the IPAddress type is already handled through the Casting to [IpAddress].
